#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace POC自动打包上线
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SPDAct")]
	public partial class DataClasses2DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertActPic(ActPic instance);
    partial void UpdateActPic(ActPic instance);
    partial void DeleteActPic(ActPic instance);
    #endregion
		
		public DataClasses2DataContext() : 
				base(global::POC自动打包上线.Properties.Settings.Default.SPDActConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ActPic> ActPic
		{
			get
			{
				return this.GetTable<ActPic>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Act")]
	public partial class ActPic : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ActID;
		
		private string _ActName;
		
		private string _FileNumber;
		
		private System.Nullable<System.DateTime> _Pub_Date;
		
		private System.Nullable<System.DateTime> _Sta_Date;
		
		private string _Depts;
		
		private System.Nullable<int> _State;
		
		private System.Nullable<System.DateTime> _OpDate;
		
		private System.Nullable<int> _Effect;
		
		private string _XmlContent;
		
		private int _ID;
		
		private System.Nullable<int> _PictureState;
		
		private string _operator;
		
		private string _Source;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnActIDChanging(int value);
    partial void OnActIDChanged();
    partial void OnActNameChanging(string value);
    partial void OnActNameChanged();
    partial void OnFileNumberChanging(string value);
    partial void OnFileNumberChanged();
    partial void OnPub_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnPub_DateChanged();
    partial void OnSta_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnSta_DateChanged();
    partial void OnDeptsChanging(string value);
    partial void OnDeptsChanged();
    partial void OnStateChanging(System.Nullable<int> value);
    partial void OnStateChanged();
    partial void OnOpDateChanging(System.Nullable<System.DateTime> value);
    partial void OnOpDateChanged();
    partial void OnEffectChanging(System.Nullable<int> value);
    partial void OnEffectChanged();
    partial void OnXmlContentChanging(string value);
    partial void OnXmlContentChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPictureStateChanging(System.Nullable<int> value);
    partial void OnPictureStateChanged();
    partial void OnoperatorChanging(string value);
    partial void OnoperatorChanged();
    partial void OnSourceChanging(string value);
    partial void OnSourceChanged();
    #endregion
		
		public ActPic()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ActID
		{
			get
			{
				return this._ActID;
			}
			set
			{
				if ((this._ActID != value))
				{
					this.OnActIDChanging(value);
					this.SendPropertyChanging();
					this._ActID = value;
					this.SendPropertyChanged("ActID");
					this.OnActIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActName", DbType="NVarChar(500)")]
		public string ActName
		{
			get
			{
				return this._ActName;
			}
			set
			{
				if ((this._ActName != value))
				{
					this.OnActNameChanging(value);
					this.SendPropertyChanging();
					this._ActName = value;
					this.SendPropertyChanged("ActName");
					this.OnActNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileNumber", DbType="NVarChar(MAX)")]
		public string FileNumber
		{
			get
			{
				return this._FileNumber;
			}
			set
			{
				if ((this._FileNumber != value))
				{
					this.OnFileNumberChanging(value);
					this.SendPropertyChanging();
					this._FileNumber = value;
					this.SendPropertyChanged("FileNumber");
					this.OnFileNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pub_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Pub_Date
		{
			get
			{
				return this._Pub_Date;
			}
			set
			{
				if ((this._Pub_Date != value))
				{
					this.OnPub_DateChanging(value);
					this.SendPropertyChanging();
					this._Pub_Date = value;
					this.SendPropertyChanged("Pub_Date");
					this.OnPub_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sta_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Sta_Date
		{
			get
			{
				return this._Sta_Date;
			}
			set
			{
				if ((this._Sta_Date != value))
				{
					this.OnSta_DateChanging(value);
					this.SendPropertyChanging();
					this._Sta_Date = value;
					this.SendPropertyChanged("Sta_Date");
					this.OnSta_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Depts", DbType="NVarChar(MAX)")]
		public string Depts
		{
			get
			{
				return this._Depts;
			}
			set
			{
				if ((this._Depts != value))
				{
					this.OnDeptsChanging(value);
					this.SendPropertyChanging();
					this._Depts = value;
					this.SendPropertyChanged("Depts");
					this.OnDeptsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="Int")]
		public System.Nullable<int> State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OpDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> OpDate
		{
			get
			{
				return this._OpDate;
			}
			set
			{
				if ((this._OpDate != value))
				{
					this.OnOpDateChanging(value);
					this.SendPropertyChanging();
					this._OpDate = value;
					this.SendPropertyChanged("OpDate");
					this.OnOpDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Effect", DbType="Int")]
		public System.Nullable<int> Effect
		{
			get
			{
				return this._Effect;
			}
			set
			{
				if ((this._Effect != value))
				{
					this.OnEffectChanging(value);
					this.SendPropertyChanging();
					this._Effect = value;
					this.SendPropertyChanged("Effect");
					this.OnEffectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XmlContent", DbType="NVarChar(MAX)")]
		public string XmlContent
		{
			get
			{
				return this._XmlContent;
			}
			set
			{
				if ((this._XmlContent != value))
				{
					this.OnXmlContentChanging(value);
					this.SendPropertyChanging();
					this._XmlContent = value;
					this.SendPropertyChanged("XmlContent");
					this.OnXmlContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PictureState", DbType="Int")]
		public System.Nullable<int> PictureState
		{
			get
			{
				return this._PictureState;
			}
			set
			{
				if ((this._PictureState != value))
				{
					this.OnPictureStateChanging(value);
					this.SendPropertyChanging();
					this._PictureState = value;
					this.SendPropertyChanged("PictureState");
					this.OnPictureStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="operator", Storage="_operator", DbType="NVarChar(256)")]
		public string @operator
		{
			get
			{
				return this._operator;
			}
			set
			{
				if ((this._operator != value))
				{
					this.OnoperatorChanging(value);
					this.SendPropertyChanging();
					this._operator = value;
					this.SendPropertyChanged("@operator");
					this.OnoperatorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Source", DbType="NVarChar(256)")]
		public string Source
		{
			get
			{
				return this._Source;
			}
			set
			{
				if ((this._Source != value))
				{
					this.OnSourceChanging(value);
					this.SendPropertyChanging();
					this._Source = value;
					this.SendPropertyChanged("Source");
					this.OnSourceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
