#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace POC自动打包上线
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SPDAct")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertAct(Act instance);
    partial void UpdateAct(Act instance);
    partial void DeleteAct(Act instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::POC自动打包上线.Properties.Settings.Default.SPDActConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Act> Act
		{
			get
			{
				return this.GetTable<Act>();
			}
		}
		
		public System.Data.Linq.Table<Act_Items> Act_Items
		{
			get
			{
				return this.GetTable<Act_Items>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UPload_Data")]
		public int UPload_Data()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UPload_Data_Friday")]
		public int UPload_Data_Friday([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallDateTime")] System.Nullable<System.DateTime> datetime)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), datetime);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UPload_Data_Friday2")]
		public int UPload_Data_Friday2([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallDateTime")] System.Nullable<System.DateTime> datetime)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), datetime);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Act")]
	public partial class Act : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ActID;
		
		private int _Act_Level;
		
		private short _Act_Order;
		
		private System.Nullable<short> _Effect;
		
		private System.Nullable<System.DateTime> _Enb_Date;
		
		private System.Nullable<System.DateTime> _Pub_Date;
		
		private System.Nullable<System.DateTime> _Sta_Date;
		
		private System.Nullable<System.DateTime> _End_Date;
		
		private string _Province;
		
		private string _Act_Name;
		
		private System.Nullable<System.DateTime> _Upload_date;
		
		private string _operator;
		
		private System.DateTime _op_date;
		
		private string _Content;
		
		private byte _IsOnline;
		
		private System.Guid _GID;
		
		private string _fileNumber;
		
		private string _Check_Name;
		
		private byte _IsError;
		
		private string _Source;
		
		private string _SourceCN;
		
		private System.Nullable<int> _EditState;
		
		private int _FromType;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnActIDChanging(int value);
    partial void OnActIDChanged();
    partial void OnAct_LevelChanging(int value);
    partial void OnAct_LevelChanged();
    partial void OnAct_OrderChanging(short value);
    partial void OnAct_OrderChanged();
    partial void OnEffectChanging(System.Nullable<short> value);
    partial void OnEffectChanged();
    partial void OnEnb_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnEnb_DateChanged();
    partial void OnPub_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnPub_DateChanged();
    partial void OnSta_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnSta_DateChanged();
    partial void OnEnd_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnEnd_DateChanged();
    partial void OnProvinceChanging(string value);
    partial void OnProvinceChanged();
    partial void OnAct_NameChanging(string value);
    partial void OnAct_NameChanged();
    partial void OnUpload_dateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpload_dateChanged();
    partial void OnoperatorChanging(string value);
    partial void OnoperatorChanged();
    partial void Onop_dateChanging(System.DateTime value);
    partial void Onop_dateChanged();
    partial void OnContentChanging(string value);
    partial void OnContentChanged();
    partial void OnIsOnlineChanging(byte value);
    partial void OnIsOnlineChanged();
    partial void OnGIDChanging(System.Guid value);
    partial void OnGIDChanged();
    partial void OnfileNumberChanging(string value);
    partial void OnfileNumberChanged();
    partial void OnCheck_NameChanging(string value);
    partial void OnCheck_NameChanged();
    partial void OnIsErrorChanging(byte value);
    partial void OnIsErrorChanged();
    partial void OnSourceChanging(string value);
    partial void OnSourceChanged();
    partial void OnSourceCNChanging(string value);
    partial void OnSourceCNChanged();
    partial void OnEditStateChanging(System.Nullable<int> value);
    partial void OnEditStateChanged();
    partial void OnFromTypeChanging(int value);
    partial void OnFromTypeChanged();
    #endregion
		
		public Act()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ActID
		{
			get
			{
				return this._ActID;
			}
			set
			{
				if ((this._ActID != value))
				{
					this.OnActIDChanging(value);
					this.SendPropertyChanging();
					this._ActID = value;
					this.SendPropertyChanged("ActID");
					this.OnActIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Act_Level", DbType="Int NOT NULL")]
		public int Act_Level
		{
			get
			{
				return this._Act_Level;
			}
			set
			{
				if ((this._Act_Level != value))
				{
					this.OnAct_LevelChanging(value);
					this.SendPropertyChanging();
					this._Act_Level = value;
					this.SendPropertyChanged("Act_Level");
					this.OnAct_LevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Act_Order", DbType="SmallInt NOT NULL")]
		public short Act_Order
		{
			get
			{
				return this._Act_Order;
			}
			set
			{
				if ((this._Act_Order != value))
				{
					this.OnAct_OrderChanging(value);
					this.SendPropertyChanging();
					this._Act_Order = value;
					this.SendPropertyChanged("Act_Order");
					this.OnAct_OrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Effect", DbType="SmallInt")]
		public System.Nullable<short> Effect
		{
			get
			{
				return this._Effect;
			}
			set
			{
				if ((this._Effect != value))
				{
					this.OnEffectChanging(value);
					this.SendPropertyChanging();
					this._Effect = value;
					this.SendPropertyChanged("Effect");
					this.OnEffectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Enb_Date", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> Enb_Date
		{
			get
			{
				return this._Enb_Date;
			}
			set
			{
				if ((this._Enb_Date != value))
				{
					this.OnEnb_DateChanging(value);
					this.SendPropertyChanging();
					this._Enb_Date = value;
					this.SendPropertyChanged("Enb_Date");
					this.OnEnb_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pub_Date", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> Pub_Date
		{
			get
			{
				return this._Pub_Date;
			}
			set
			{
				if ((this._Pub_Date != value))
				{
					this.OnPub_DateChanging(value);
					this.SendPropertyChanging();
					this._Pub_Date = value;
					this.SendPropertyChanged("Pub_Date");
					this.OnPub_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sta_Date", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> Sta_Date
		{
			get
			{
				return this._Sta_Date;
			}
			set
			{
				if ((this._Sta_Date != value))
				{
					this.OnSta_DateChanging(value);
					this.SendPropertyChanging();
					this._Sta_Date = value;
					this.SendPropertyChanged("Sta_Date");
					this.OnSta_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_End_Date", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> End_Date
		{
			get
			{
				return this._End_Date;
			}
			set
			{
				if ((this._End_Date != value))
				{
					this.OnEnd_DateChanging(value);
					this.SendPropertyChanging();
					this._End_Date = value;
					this.SendPropertyChanged("End_Date");
					this.OnEnd_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Province", DbType="NVarChar(20)")]
		public string Province
		{
			get
			{
				return this._Province;
			}
			set
			{
				if ((this._Province != value))
				{
					this.OnProvinceChanging(value);
					this.SendPropertyChanging();
					this._Province = value;
					this.SendPropertyChanged("Province");
					this.OnProvinceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Act_Name", DbType="NVarChar(500)")]
		public string Act_Name
		{
			get
			{
				return this._Act_Name;
			}
			set
			{
				if ((this._Act_Name != value))
				{
					this.OnAct_NameChanging(value);
					this.SendPropertyChanging();
					this._Act_Name = value;
					this.SendPropertyChanged("Act_Name");
					this.OnAct_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Upload_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Upload_date
		{
			get
			{
				return this._Upload_date;
			}
			set
			{
				if ((this._Upload_date != value))
				{
					this.OnUpload_dateChanging(value);
					this.SendPropertyChanging();
					this._Upload_date = value;
					this.SendPropertyChanged("Upload_date");
					this.OnUpload_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="operator", Storage="_operator", DbType="NVarChar(20)")]
		public string @operator
		{
			get
			{
				return this._operator;
			}
			set
			{
				if ((this._operator != value))
				{
					this.OnoperatorChanging(value);
					this.SendPropertyChanging();
					this._operator = value;
					this.SendPropertyChanged("@operator");
					this.OnoperatorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_op_date", DbType="DateTime NOT NULL")]
		public System.DateTime op_date
		{
			get
			{
				return this._op_date;
			}
			set
			{
				if ((this._op_date != value))
				{
					this.Onop_dateChanging(value);
					this.SendPropertyChanging();
					this._op_date = value;
					this.SendPropertyChanged("op_date");
					this.Onop_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Content", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Content
		{
			get
			{
				return this._Content;
			}
			set
			{
				if ((this._Content != value))
				{
					this.OnContentChanging(value);
					this.SendPropertyChanging();
					this._Content = value;
					this.SendPropertyChanged("Content");
					this.OnContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsOnline", DbType="TinyInt NOT NULL")]
		public byte IsOnline
		{
			get
			{
				return this._IsOnline;
			}
			set
			{
				if ((this._IsOnline != value))
				{
					this.OnIsOnlineChanging(value);
					this.SendPropertyChanging();
					this._IsOnline = value;
					this.SendPropertyChanged("IsOnline");
					this.OnIsOnlineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GID
		{
			get
			{
				return this._GID;
			}
			set
			{
				if ((this._GID != value))
				{
					this.OnGIDChanging(value);
					this.SendPropertyChanging();
					this._GID = value;
					this.SendPropertyChanged("GID");
					this.OnGIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fileNumber", DbType="NVarChar(150)")]
		public string fileNumber
		{
			get
			{
				return this._fileNumber;
			}
			set
			{
				if ((this._fileNumber != value))
				{
					this.OnfileNumberChanging(value);
					this.SendPropertyChanging();
					this._fileNumber = value;
					this.SendPropertyChanged("fileNumber");
					this.OnfileNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Check_Name", DbType="NVarChar(250)")]
		public string Check_Name
		{
			get
			{
				return this._Check_Name;
			}
			set
			{
				if ((this._Check_Name != value))
				{
					this.OnCheck_NameChanging(value);
					this.SendPropertyChanging();
					this._Check_Name = value;
					this.SendPropertyChanged("Check_Name");
					this.OnCheck_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsError", DbType="TinyInt NOT NULL")]
		public byte IsError
		{
			get
			{
				return this._IsError;
			}
			set
			{
				if ((this._IsError != value))
				{
					this.OnIsErrorChanging(value);
					this.SendPropertyChanging();
					this._IsError = value;
					this.SendPropertyChanged("IsError");
					this.OnIsErrorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Source", DbType="NVarChar(300)")]
		public string Source
		{
			get
			{
				return this._Source;
			}
			set
			{
				if ((this._Source != value))
				{
					this.OnSourceChanging(value);
					this.SendPropertyChanging();
					this._Source = value;
					this.SendPropertyChanged("Source");
					this.OnSourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SourceCN", DbType="NVarChar(500)")]
		public string SourceCN
		{
			get
			{
				return this._SourceCN;
			}
			set
			{
				if ((this._SourceCN != value))
				{
					this.OnSourceCNChanging(value);
					this.SendPropertyChanging();
					this._SourceCN = value;
					this.SendPropertyChanged("SourceCN");
					this.OnSourceCNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditState", DbType="Int")]
		public System.Nullable<int> EditState
		{
			get
			{
				return this._EditState;
			}
			set
			{
				if ((this._EditState != value))
				{
					this.OnEditStateChanging(value);
					this.SendPropertyChanging();
					this._EditState = value;
					this.SendPropertyChanged("EditState");
					this.OnEditStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FromType", DbType="Int NOT NULL")]
		public int FromType
		{
			get
			{
				return this._FromType;
			}
			set
			{
				if ((this._FromType != value))
				{
					this.OnFromTypeChanging(value);
					this.SendPropertyChanging();
					this._FromType = value;
					this.SendPropertyChanged("FromType");
					this.OnFromTypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Act_Items")]
	public partial class Act_Items
	{
		
		private int _ItemID;
		
		private int _ActID;
		
		private System.Nullable<short> _Item_Name;
		
		private System.Nullable<byte> _Item_Type;
		
		private System.Nullable<int> _orders;
		
		private string _Content;
		
		private System.Nullable<int> _Item_ParentID;
		
		public Act_Items()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemID", DbType="Int NOT NULL")]
		public int ItemID
		{
			get
			{
				return this._ItemID;
			}
			set
			{
				if ((this._ItemID != value))
				{
					this._ItemID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActID", DbType="Int NOT NULL")]
		public int ActID
		{
			get
			{
				return this._ActID;
			}
			set
			{
				if ((this._ActID != value))
				{
					this._ActID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_Name", DbType="SmallInt")]
		public System.Nullable<short> Item_Name
		{
			get
			{
				return this._Item_Name;
			}
			set
			{
				if ((this._Item_Name != value))
				{
					this._Item_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_Type", DbType="TinyInt")]
		public System.Nullable<byte> Item_Type
		{
			get
			{
				return this._Item_Type;
			}
			set
			{
				if ((this._Item_Type != value))
				{
					this._Item_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orders", DbType="Int")]
		public System.Nullable<int> orders
		{
			get
			{
				return this._orders;
			}
			set
			{
				if ((this._orders != value))
				{
					this._orders = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Content", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Content
		{
			get
			{
				return this._Content;
			}
			set
			{
				if ((this._Content != value))
				{
					this._Content = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_ParentID", DbType="Int")]
		public System.Nullable<int> Item_ParentID
		{
			get
			{
				return this._Item_ParentID;
			}
			set
			{
				if ((this._Item_ParentID != value))
				{
					this._Item_ParentID = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
